Platform.getInfo('kubejs').name = 'Craftopia'

StartupEvents.registry('item', e => {

  e.create('abyssal_plate')
  e.create('amber_ingot')
  e.create('amethyst_bronze_plate')
  e.create('calorite_plate')
  e.create('cobalt_plate')
  e.create('desh_plate')
  e.create('dragonsteel_plate')
  e.create('evil_tear')
  e.create('fiery_plate')
  e.create('ironwood_plate')
  e.create('hepatizon_plate')
  e.create('knightmetal_plate')
  e.create('manyullyn_plate')
  e.create('netherite_plate')
  e.create('ostrum_plate')
  e.create('pig_iron_plate')
  e.create('queens_slime_plate')
  e.create('refined_glowstone_plate')
  e.create('refined_obsidian_plate')
  e.create('rose_gold_plate')
  e.create('shellite_plate')
  e.create('slimesteel_plate')
  e.create('soul_infused_plate')
  e.create('sturdy_plate')
  e.create('twinite_plate')
  e.create('vanadium_plate')
})