// Items
JEIEvents.hideItems(craftopia => {
  craftopia.hide(Item.of('ad_astra:energizer', '{BotariumData:{Energy:2000000L}}'))
  craftopia.hide(Item.of('ad_astra:etrionic_capacitor', '{BotariumData:{Energy:250000L}}'))
  craftopia.hide(Item.of('ad_astra:gas_tank', '{BotariumData:{StoredFluids:[{Amount:1000L,Fluid:"ad_astra:oxygen"}]}}'))
  craftopia.hide(Item.of('ad_astra:jet_suit', '{BotariumData:{Energy:1000000L,StoredFluids:[{Amount:4000L,Fluid:"ad_astra:oxygen"}]},Damage:0}'))
  craftopia.hide(Item.of('ad_astra:large_gas_tank', '{BotariumData:{StoredFluids:[{Amount:3000L,Fluid:"ad_astra:oxygen"}]}}'))
  craftopia.hide(Item.of('ad_astra:netherite_space_suit', '{BotariumData:{StoredFluids:[{Amount:2000L,Fluid:"ad_astra:oxygen"}]},Damage:0}'))
  craftopia.hide(Item.of('ad_astra:space_suit', '{BotariumData:{StoredFluids:[{Amount:1000L,Fluid:"ad_astra:oxygen"}]},Damage:0}'))
  craftopia.hide(Item.of('ad_astra:tier_1_rocket', '{BotariumData:{StoredFluids:[{Amount:3000L,Fluid:"ad_astra:fuel"}]}}'))
  craftopia.hide(Item.of('ad_astra:tier_2_rocket', '{BotariumData:{StoredFluids:[{Amount:3000L,Fluid:"ad_astra:fuel"}]}}'))
  craftopia.hide(Item.of('ad_astra:tier_3_rocket', '{BotariumData:{StoredFluids:[{Amount:3000L,Fluid:"ad_astra:fuel"}]}}'))
  craftopia.hide(Item.of('ad_astra:tier_4_rocket', '{BotariumData:{StoredFluids:[{Amount:3000L,Fluid:"ad_astra:fuel"}]}}'))
  craftopia.hide(Item.of('ad_astra:tier_1_rover', '{BotariumData:{StoredFluids:[{Amount:3000L,Fluid:"ad_astra:fuel"}]}}'))
  craftopia.hide(Item.of('ad_astra:zip_gun', '{BotariumData:{StoredFluids:[{Amount:3000L,Fluid:"ad_astra:oxygen"}]}}'))
  craftopia.hide(Item.of('mekanism:advanced_energy_cube', '{mekData:{EnergyContainers:[{Container:0b,stored:"16000000"}]}}'))
  craftopia.hide(Item.of('mekanism:atomic_disassembler', '{mekData:{EnergyContainers:[{Container:0b,stored:"1000000"}]}}'))
  craftopia.hide(Item.of('mekanism:basic_energy_cube', '{mekData:{EnergyContainers:[{Container:0b,stored:"4000000"}]}}'))
  craftopia.hide(Item.of('mekanism:canteen', '{mekData:{FluidTanks:[{Tank:0b,stored:{Amount:64000,FluidName:"mekanism:nutritional_paste"}}]}}'))
  craftopia.hide(Item.of('mekanism:configurator', '{mekData:{EnergyContainers:[{Container:0b,stored:"60000"}]}}'))
  craftopia.hide(Item.of('mekanism:creative_energy_cube', '{mekData:{EnergyContainers:[{Container:0b,stored:"18446744073709551615.9999"}],componentConfig:{config0:{side0:4,side1:4,side2:4,side3:4,side4:4,side5:4}}}}'))
  craftopia.hide(Item.of('mekanism:electric_bow', '{mekData:{EnergyContainers:[{Container:0b,stored:"120000"}]}}'))
  craftopia.hide(Item.of('mekanism:elite_energy_cube', '{mekData:{EnergyContainers:[{Container:0b,stored:"64000000"}]}}'))
  craftopia.hide(Item.of('mekanism:energy_tablet', '{mekData:{EnergyContainers:[{Container:0b,stored:"1000000"}]}}'))
  craftopia.hide(Item.of('mekanism:portable_teleporter', '{mekData:{EnergyContainers:[{Container:0b,stored:"1000000"}]}}'))
  craftopia.hide(Item.of('mekanism:flamethrower', '{mekData:{GasTanks:[{Tank:0b,stored:{amount:24000L,gasName:"mekanism:hydrogen"}}]}}'))
  craftopia.hide(Item.of('mekanism:free_runners', '{mekData:{EnergyContainers:[{Container:0b,stored:"64000"}]}}'))
  craftopia.hide(Item.of('mekanism:free_runners_armored', '{mekData:{EnergyContainers:[{Container:0b,stored:"64000"}]}}'))
  craftopia.hide(Item.of('mekanism:jetpack', '{mekData:{GasTanks:[{Tank:0b,stored:{amount:24000L,gasName:"mekanism:hydrogen"}}]}}'))
  craftopia.hide(Item.of('mekanism:jetpack_armored', '{mekData:{GasTanks:[{Tank:0b,stored:{amount:24000L,gasName:"mekanism:hydrogen"}}]}}'))
  craftopia.hide(Item.of('mekanism:meka_tool', '{mekData:{EnergyContainers:[{Container:0b,stored:"16000000"}]}}'))
  craftopia.hide(Item.of('mekanism:mekasuit_bodyarmor', '{mekData:{EnergyContainers:[{Container:0b,stored:"16000000"}]}}'))
  craftopia.hide(Item.of('mekanism:mekasuit_boots', '{mekData:{EnergyContainers:[{Container:0b,stored:"16000000"}]}}'))
  craftopia.hide(Item.of('mekanism:mekasuit_helmet', '{mekData:{EnergyContainers:[{Container:0b,stored:"16000000"}]}}'))
  craftopia.hide(Item.of('mekanism:mekasuit_pants', '{mekData:{EnergyContainers:[{Container:0b,stored:"16000000"}]}}'))
  craftopia.hide(Item.of('mekanism:network_reader', '{mekData:{EnergyContainers:[{Container:0b,stored:"60000"}]}}'))
  craftopia.hide(Item.of('mekanism:robit', '{mekData:{EnergyContainers:[{Container:0b,stored:"100000"}]}}'))
  craftopia.hide(Item.of('mekanism:scuba_tank', '{mekData:{GasTanks:[{Tank:0b,stored:{amount:24000L,gasName:"mekanism:oxygen"}}]}}'))
  craftopia.hide(Item.of('mekanism:seismic_reader', '{mekData:{EnergyContainers:[{Container:0b,stored:"12000"}]}}'))
  craftopia.hide(Item.of('mekanism:ultimate_energy_cube', '{mekData:{EnergyContainers:[{Container:0b,stored:"256000000"}]}}'))
  craftopia.hide(Item.of('mekanismgenerators:hohlraum', '{mekData:{GasTanks:[{Tank:0b,stored:{amount:10L,gasName:"mekanismgenerators:fusion_fuel"}}]}}'))
  craftopia.hide(Item.of('minecraft:goat_horn', '{instrument:"minecraft:admire_goat_horn"}'))
  craftopia.hide(Item.of('minecraft:goat_horn', '{instrument:"minecraft:call_goat_horn"}'))
  craftopia.hide(Item.of('minecraft:goat_horn', '{instrument:"minecraft:dream_goat_horn"}'))
  craftopia.hide(Item.of('minecraft:goat_horn', '{instrument:"minecraft:feel_goat_horn"}'))
  craftopia.hide(Item.of('minecraft:goat_horn', '{instrument:"minecraft:ponder_goat_horn"}'))
  craftopia.hide(Item.of('minecraft:goat_horn', '{instrument:"minecraft:seek_goat_horn"}'))
  craftopia.hide(Item.of('minecraft:goat_horn', '{instrument:"minecraft:sing_goat_horn"}'))
  craftopia.hide(Item.of('minecraft:goat_horn', '{instrument:"minecraft:yearn_goat_horn"}'))
  craftopia.hide(Item.of('patchouli:guide_book', '{"patchouli:book":"ad_astra:astrodux"}'))
  craftopia.hide(Item.of('patchouli:guide_book', '{"patchouli:book":"buildinggadgets2:buildinggadgets2book"}'))
  craftopia.hide(Item.of('patchouli:guide_book', '{"patchouli:book":"industrialforegoing:industrial_foregoing"}'))
  craftopia.hide(Item.of('pneumaticcraft:air_canister', '{"pneumaticcraft:air":30000}'))
  craftopia.hide(Item.of('pneumaticcraft:amadron_tablet', '{"pneumaticcraft:air":30000}'))
  craftopia.hide(Item.of('pneumaticcraft:camo_applicator', '{"pneumaticcraft:air":30000}'))
  craftopia.hide(Item.of('pneumaticcraft:empty_pcb', '{"pneumaticcraft:uv_exposure":100}'))
  craftopia.hide(Item.of('pneumaticcraft:pneumatic_wrench', '{"pneumaticcraft:air":30000}'))
  craftopia.hide(Item.of('pneumaticcraft:reinforced_air_canister', '{"pneumaticcraft:air":120000}'))
  craftopia.hide(Item.of('pneumaticcraft:vortex_cannon', '{"pneumaticcraft:air":30000}'))
  craftopia.hide(Item.of('quark:backpack', '{Inventory:[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}]}'))

  // AD ASTRA
  craftopia.hide('ad_astra:calorite_plate')
  craftopia.hide('ad_astra:desh_plate')
  craftopia.hide('ad_astra:etrium_ingot')
  craftopia.hide('ad_astra:etrium_nugget')
  craftopia.hide('ad_astra:etrium_plate')
  craftopia.hide('ad_astra:etrium_rod')
  craftopia.hide('ad_astra:iron_plate')
  craftopia.hide('ad_astra:iron_rod')
  craftopia.hide('ad_astra:ostrum_plate')
  craftopia.hide('ad_astra:steel_ingot')
  craftopia.hide('ad_astra:steel_nugget')
  craftopia.hide('ad_astra:steel_plate')
  craftopia.hide('ad_astra:steel_rod')
  craftopia.hide('allthemodium:spawn_egg/piglich')

  // BYG
  craftopia.hide('biomeswevegone:barrel_cactus')
  craftopia.hide('biomeswevegone:carved_barrel_cactus')
  craftopia.hide('biomeswevegone:flowering_barrel_cactus')

  // CREATE
  craftopia.hide('create:brass_sheet')
  craftopia.hide('create:copper_sheet')
  craftopia.hide('create:golden_sheet')
  craftopia.hide('create:iron_sheet')
  craftopia.hide('create:sturdy_sheet')

  // CREATE ADDITION
  craftopia.hide('createaddition:electrum_sheet')
  craftopia.hide('createaddition:steel_sheet')
  craftopia.hide('createaddition:zinc_sheet')

  // CREATE DECO
  craftopia.hide('createdeco:andesite_sheet')
  craftopia.hide('createdeco:industrial_iron_sheet')
  craftopia.hide('createdeco:netherite_sheet')
  craftopia.hide('createdeco:zinc_sheet')

  // CREATE CENTRAK KITCHEN
  craftopia.hide('create_central_kitchen:incomplete_egg_sandwich')

  // CYCLIC
  craftopia.hide('cyclic:altar_destruction')
  craftopia.hide('cyclic:anti_beacon')
  craftopia.hide('cyclic:beacon')
  craftopia.hide('cyclic:beacon_redstone')
  craftopia.hide('cyclic:blockstate_data')
  craftopia.hide('cyclic:chorus_spectral')
  craftopia.hide('cyclic:computer_shape')
  craftopia.hide('cyclic:compressed_cobblestone')
  craftopia.hide('cyclic:copper_lantern')
  craftopia.hide('cyclic:copper_soul_lantern')
  craftopia.hide('cyclic:crafter')
  craftopia.hide('cyclic:crafting_bag')
  craftopia.hide('cyclic:crafting_stick')
  craftopia.hide('cyclic:dark_glass')
  craftopia.hide('cyclic:detector_moon')
  craftopia.hide('cyclic:dice')
  craftopia.hide('cyclic:disenchanter')
  craftopia.hide('cyclic:ender_book')
  craftopia.hide('cyclic:energy_pipe')
  craftopia.hide('cyclic:entity_data')
  craftopia.hide('cyclic:fan')
  craftopia.hide('cyclic:fan_slab')
  craftopia.hide('cyclic:filter_data')
  craftopia.hide('cyclic:fireplace')
  craftopia.hide('cyclic:fisher')
  craftopia.hide('cyclic:fluid_pipe')
  craftopia.hide('cyclic:flute_summoning')
  craftopia.hide('cyclic:generator_fluid')
  craftopia.hide('cyclic:generator_food')
  craftopia.hide('cyclic:generator_fuel')
  craftopia.hide('cyclic:generator_item')
  craftopia.hide('cyclic:generator_solar')
  craftopia.hide('cyclic:ghost_phantom')
  craftopia.hide('cyclic:gold_bars')
  craftopia.hide('cyclic:gold_lantern')
  craftopia.hide('cyclic:gold_soul_lantern')
  craftopia.hide('cyclic:heart')
  craftopia.hide('cyclic:heart_empty')
  craftopia.hide('cyclic:item_pipe')
  craftopia.hide('cyclic:lever_remote')
  craftopia.hide('cyclic:location_data')
  craftopia.hide('cyclic:mob_container')
  craftopia.hide('cyclic:no_soliciting')
  craftopia.hide('cyclic:obsidian_pressure_plate')
  craftopia.hide('cyclic:packager')
  craftopia.hide('cyclic:plate_launch')
  craftopia.hide('cyclic:plate_launch_redstone')
  craftopia.hide('cyclic:quiver_damage')
  craftopia.hide('cyclic:quiver_lightning')
  craftopia.hide('cyclic:rotator')
  craftopia.hide('cyclic:scaffold_fragile')
  craftopia.hide('cyclic:scaffold_replace')
  craftopia.hide('cyclic:scaffold_responsive')
  craftopia.hide('cyclic:screen')
  craftopia.hide('cyclic:settings_data')
  craftopia.hide('cyclic:shape_data')
  craftopia.hide('cyclic:slingshot')
  craftopia.hide('cyclic:sound_data')
  craftopia.hide('cyclic:sound_player')
  craftopia.hide('cyclic:sound_recorder')
  craftopia.hide('cyclic:soundproofing')
  craftopia.hide('cyclic:soundproofing_ghost')
  craftopia.hide('cyclic:spawner_seeker')
  craftopia.hide('cyclic:spikes_curse')
  craftopia.hide('cyclic:spikes_diamond')
  craftopia.hide('cyclic:spikes_fire')
  craftopia.hide('cyclic:spikes_iron')
  craftopia.hide('cyclic:sprinkler')
  craftopia.hide('cyclic:storage_bag')
  craftopia.hide('cyclic:structure')
  craftopia.hide('cyclic:teleport')
  craftopia.hide('cyclic:terra_glass')
  craftopia.hide('cyclic:terra_preta')
  craftopia.hide('cyclic:tile_transporter')
  craftopia.hide('cyclic:tile_transporter_empty')
  craftopia.hide('cyclic:trash')
  craftopia.hide('cyclic:unbreakable_block')
  craftopia.hide('cyclic:unbreakable_reactive')
  craftopia.hide('cyclic:user')
  craftopia.hide('cyclic:wand_hypno')
  craftopia.hide('cyclic:wand_mssile')
  craftopia.hide('cyclic:water_candle')
  craftopia.hide('cyclic:waxed_redstone')
  craftopia.hide('cyclic:wireless_item')
  craftopia.hide('cyclic:wireless_fluid')
  craftopia.hide('cyclic:wireless_item')
  craftopia.hide('cyclic:wireless_receiver')
  craftopia.hide('cyclic:wireless_transmitter')

  // DECORATIVE BLOCKS
  craftopia.hide('decorative_blocks:blockstate_copy_item')

  // DISPLAY CASE
  craftopia.hide('display_case:display_case_lid')

  // ECOLOGICS
  craftopia.hide('ecologics:crab_meat')

  // ENDER IO
  craftopia.hide('enderio:capacitor')
  craftopia.hide('enderio:light')
  craftopia.hide('enderio:light_inverted')
  craftopia.hide('enderio:location_printout')
  craftopia.hide('enderio:powered_light')
  craftopia.hide('enderio:powered_light_inverted')
  craftopia.hide('enderio:powered_light_wireless')
  craftopia.hide('enderio:powered_light_inverted_wireless')

  // IMMERSIVE ENGINEERING
  craftopia.hide('immersiveengineering:nugget_copper')
  craftopia.hide('immersiveengineering:plate_aluminum')
  craftopia.hide('immersiveengineering:plate_constantan')
  craftopia.hide('immersiveengineering:plate_copper')
  craftopia.hide('immersiveengineering:plate_duroplast')
  craftopia.hide('immersiveengineering:plate_electrum')
  craftopia.hide('immersiveengineering:plate_gold')
  craftopia.hide('immersiveengineering:plate_iron')
  craftopia.hide('immersiveengineering:plate_lead')
  craftopia.hide('immersiveengineering:plate_nickel')
  craftopia.hide('immersiveengineering:plate_silver')
  craftopia.hide('immersiveengineering:plate_steel')
  craftopia.hide('immersiveengineering:plate_uranium')

  // IRON CHEST
  craftopia.hide('ironchest:dirt_chest')
  craftopia.hide('ironchest:trapped_dirt_chest')

  // IRON FURNACES
  craftopia.hide('ironfurnaces:copper_furnace')
  craftopia.hide('ironfurnaces:crystal_furnace')
  craftopia.hide('ironfurnaces:silver_furnace')

  // IRONS SPELLBOOKS
  craftopia.hide('irons_spellbooks:armor_pile')
  craftopia.hide('irons_spellbooks:blood_staff')
  craftopia.hide('irons_spellbooks:blood_vial')

  // MEKANISM
  craftopia.hide('mekanism:block_bronze')
  craftopia.hide('mekanism:dust_bronze')
  craftopia.hide('mekanism:ingot_bronze')
  craftopia.hide('mekanism:nugget_bronze')
  craftopia.hide('mekanism:block_tin')
  craftopia.hide('mekanism:dust_tin')
  craftopia.hide('mekanism:ingot_tin')
  craftopia.hide('mekanism:nugget_tin')

  // MINECRAFT
  craftopia.hide('minecraft:barrier')
  craftopia.hide('minecraft:chain_command_block')
  craftopia.hide('minecraft:command_block')
  craftopia.hide('minecraft:command_block_minecart')
  craftopia.hide('minecraft:debug_stick')
  craftopia.hide('minecraft:jigsaw')
  craftopia.hide('minecraft:light')
  craftopia.hide('minecraft:repeating_command_block')
  craftopia.hide('minecraft:structure_block')
  craftopia.hide('minecraft:structure_void')

  // MOB GRINDING UTILS
  craftopia.hide('mob_grinding_utils:dark_oak_stone')
  craftopia.hide('mob_grinding_utils:ender_inhibitor_off')
  craftopia.hide('mob_grinding_utils:mob_swab_used')

  // PNEUMATICCRAFT
  craftopia.hide('pneumaticcraft:collector_drone')
  craftopia.hide('pneumaticcraft:copper_nugget')
  craftopia.hide('pneumaticcraft:drone')
  craftopia.hide('pneumaticcraft:guard_drone')
  craftopia.hide('pneumaticcraft:harvesting_drone')
  craftopia.hide('pneumaticcraft:jackhammer')
  craftopia.hide('pneumaticcraft:logistics_drone')
  craftopia.hide('pneumaticcraft:manometer')
  craftopia.hide('pneumaticcraft:minigun')

  // QUARK
  craftopia.hide('quark:bottled_cloud')
  craftopia.hide('quark:magnet')

  // SHRINK
  craftopia.hide('shrink:mob_bottle')

  // THERMAL EXTRA
  craftopia.hide('thermal_extra:abyssal_plate')
  craftopia.hide('thermal_extra:dragonsteel_plate')
  craftopia.hide('thermal_extra:shellite_plate')
  craftopia.hide('thermal_extra:soul_infused_plate')
  craftopia.hide('thermal_extra:twinite_plate')

  // THERMAL
  craftopia.hide('thermal:bronze_block')
  craftopia.hide('thermal:bronze_dust')
  craftopia.hide('thermal:bronze_gear')
  craftopia.hide('thermal:bronze_ingot')
  craftopia.hide('thermal:bronze_nugget')
  craftopia.hide('thermal:bronze_plate')
  craftopia.hide('thermal:constantan_plate')
  craftopia.hide('thermal:copper_plate')
  craftopia.hide('thermal:electrum_plate')
  craftopia.hide('thermal:enderium_plate')
  craftopia.hide('thermal:gold_plate')
  craftopia.hide('thermal:invar_plate')
  craftopia.hide('thermal:iron_plate')
  craftopia.hide('thermal:lead_plate')
  craftopia.hide('thermal:lumium_plate')
  craftopia.hide('thermal:netherite_plate')
  craftopia.hide('thermal:nickel_plate')
  craftopia.hide('thermal:rose_gold_plate')
  craftopia.hide('thermal:signalum_plate')
  craftopia.hide('thermal:silver_plate')
  craftopia.hide('thermal:steel_plate')
  craftopia.hide('thermal:tin_block')
  craftopia.hide('thermal:tin_dust')
  craftopia.hide('thermal:tin_gear')
  craftopia.hide('thermal:tin_ingot')
  craftopia.hide('thermal:tin_nugget')
  craftopia.hide('thermal:tin_plate')

  // VINTAGE 
  craftopia.hide('vintage:aluminum_sheet')
  craftopia.hide('vintage:amethyst_bronze_sheet')
  craftopia.hide('vintage:andesite_sheet')
  craftopia.hide('vintage:bronze_sheet')
  craftopia.hide('vintage:cobalt_sheet')
  craftopia.hide('vintage:constantan_sheet')
  craftopia.hide('vintage:enderium_sheet')
  craftopia.hide('vintage:fiery_sheet')
  craftopia.hide('vintage:hepatizon_sheet')
  craftopia.hide('vintage:ironwood_sheet')
  craftopia.hide('vintage:invar_sheet')
  craftopia.hide('vintage:knightmetal_sheet')
  craftopia.hide('vintage:lead_sheet')
  craftopia.hide('vintage:lumium_sheet')
  craftopia.hide('vintage:manyullyn_sheet')
  craftopia.hide('vintage:netherite_sheet')
  craftopia.hide('vintage:nickel_sheet')
  craftopia.hide('vintage:osmium_sheet')
  craftopia.hide('vintage:pig_iron_sheet')
  craftopia.hide('vintage:platinum_sheet')
  craftopia.hide('vintage:queens_slime_sheet')
  craftopia.hide('vintage:refined_glowstone_sheet')
  craftopia.hide('vintage:refined_obsidian_sheet')
  craftopia.hide('vintage:rose_gold_sheet')
  craftopia.hide('vintage:signalum_sheet')
  craftopia.hide('vintage:silver_sheet')
  craftopia.hide('vintage:slimesteel_sheet')
  craftopia.hide('vintage:tin_sheet')
  craftopia.hide('vintage:uranium_sheet')
  craftopia.hide('vintage:vanadium_sheet')
  craftopia.hide('vintage:zinc_sheet')


// REGEX
  craftopia.hide(/ae2:facade/)
  craftopia.hide(/botanypots(tiers:(elite|ultra|creative)_|:).+_(terracotta|concrete)(_hopper)?_botany_pot/)
  craftopia.hide(/enderio:broken_spawner/)
  craftopia.hide(/immersiveengineering:shader/)
  craftopia.hide(/irons_spellbooks:scroll/)
  craftopia.hide(/mekanism:creative_chemical_tank/)
  craftopia.hide(/mekanism:creative_fluid_tank/)
  craftopia.hide(/minecraft:enchanted_book/)
  craftopia.hide(/minecraft:lingering_potion/)
  craftopia.hide(/minecraft:painting/)
  craftopia.hide(/minecraft:potion/)
  craftopia.hide(/minecraft:splash_potion/)
  craftopia.hide(/minecraft:tipped_arrow/)
  craftopia.hide(/reliquary:lingering_potion/)
  craftopia.hide(/reliquary:mob_charm/)
  craftopia.hide(/reliquary:potion/)
  craftopia.hide(/reliquary:potion_essence/)
  craftopia.hide(/reliquary:splash_potion/)
  craftopia.hide(/reliquary:tipped_arrow/)
})

// Fluids
JEIEvents.hideFluids(craftopia => {
  craftopia.hide('ad_astra:cryo_fuel')
  craftopia.hide('ad_astra:fuel')
  craftopia.hide('ad_astra:hydrogen')
  craftopia.hide('ad_astra:oil')
  craftopia.hide('ad_astra:oxygen')
  craftopia.hide('allthemodium:molten_allthemodium')
  craftopia.hide('allthemodium:molten_unobtainium')
  craftopia.hide('allthemodium:molten_vibranium')
  craftopia.hide('allthemodium:soul_lava')
  craftopia.hide('biomesoplenty:blood')
  craftopia.hide('create:chocolate')
  craftopia.hide('create:honey')
  craftopia.hide('createaddition:bioethanol')
  craftopia.hide('createaddition:seed_oil')
  craftopia.hide('create_central_kitchen:tomato_sauce')
  craftopia.hide('create_confectionery:black_chocolate')
  craftopia.hide('create_confectionery:caramel')
  craftopia.hide('create_confectionery:hot_chocolate')
  craftopia.hide('create_confectionery:ruby_chocolate')
  craftopia.hide('create_confectionery:white_chocolate')
  craftopia.hide('create_enchantment_industry:experience')
  craftopia.hide('create_enchantment_industry:hyper_expereience')
  craftopia.hide('create_enchantment_industry:ink')
  craftopia.hide('cyclic:biomass')
  craftopia.hide('cyclic:honey')
  craftopia.hide('cyclic:magma')
  craftopia.hide('cyclic:slime')
  craftopia.hide('cyclic:wax')
  craftopia.hide('cyclic:xpjuice')
  craftopia.hide('enderio:cloud_seed')
  craftopia.hide('enderio:cloud_seed_concentrated')
  craftopia.hide('enderio:dew_of_the_void')
  craftopia.hide('enderio:fire_water')
  craftopia.hide('enderio:hootch')
  craftopia.hide('enderio:liquid_sunshine')
  craftopia.hide('enderio:nutrient_distillation')
  craftopia.hide('enderio:rocket_fuel')
  craftopia.hide('enderio:vapor_of_levity')
  craftopia.hide('enderio:xp_juice')
  craftopia.hide('decorative_blocks:thatch')
  craftopia.hide('immersiveengineering:acetaldehyde')
  craftopia.hide('immersiveengineering:biodiesel')
  craftopia.hide('immersiveengineering:concrete')
  craftopia.hide('immersiveengineering:creosote')
  craftopia.hide('immersiveengineering:ethanol')
  craftopia.hide('immersiveengineering:herbicide')
  craftopia.hide('immersiveengineering:phenolic_resin')
  craftopia.hide('immersiveengineering:plantoil')
  craftopia.hide('immersiveengineering:potion')
  craftopia.hide('immersiveengineering:redstone_acid')
  craftopia.hide('industrialforegoing:biofuel')
  craftopia.hide('industrialforegoing:essence')
  craftopia.hide('industrialforegoing:ether_gas')
  craftopia.hide('industrialforegoing:fermented_ore_meat')
  craftopia.hide('industrialforegoing:latex')
  craftopia.hide('industrialforegoing:meat')
  craftopia.hide('industrialforegoing:pink_slime')
  craftopia.hide('industrialforegoing:raw_ore_meat')
  craftopia.hide('industrialforegoing:sewage')
  craftopia.hide('industrialforegoing:sludge')
  craftopia.hide('integrateddynamics:liquid_chorus')
  craftopia.hide('integrateddynamics:menril_resin')
  craftopia.hide('mekanism:brine')
  craftopia.hide('mekanism:chlorine')
  craftopia.hide('mekanism:ethene')
  craftopia.hide('mekanism:heavy_water')
  craftopia.hide('mekanism:hydrofluoric_acid')
  craftopia.hide('mekanism:hydrogen')
  craftopia.hide('mekanism:hydrogen_chloride')
  craftopia.hide('mekanism:lithium')
  craftopia.hide('mekanism:nutritional_paste')
  craftopia.hide('mekanism:oxygen')
  craftopia.hide('mekanism:sodium')
  craftopia.hide('mekanism:steam')
  craftopia.hide('mekanism:sulfur_dioxide')
  craftopia.hide('mekanism:sulfur_trioxide')
  craftopia.hide('mekanism:sulfuric_acid')
  craftopia.hide('mekanism:superheated_sodium')
  craftopia.hide('mekanism:uranium_hexafluoride')
  craftopia.hide('mekanism:uranium_oxide')
  craftopia.hide('mekanismgenerators:bioethanol')
  craftopia.hide('mekanismgenerators:deuterium')
  craftopia.hide('mekanismgenerators:fusion_fuel')
  craftopia.hide('mekanismgenerators:tritium')
  craftopia.hide('mekanism_extras:fluorinated_silicon_uranium_fuel')
  craftopia.hide('mekanism_extras:polonium-208')
  craftopia.hide('mekanism_extras:polonium_containing_solution')
  craftopia.hide('mekanism_extras:rich_silicon_fuel')
  craftopia.hide('mekanism_extras:rich_uranium_fuel')
  craftopia.hide('mekanism_extras:silicon_tetrafluoride')
  craftopia.hide('minecraft:lava')
  craftopia.hide('minecraft:milk')
  craftopia.hide('minecraft:water')
  craftopia.hide('mob_grinding_utils:fluid_xp')
  craftopia.hide('mysticalagradditions:molten_imperium')
  craftopia.hide('mysticalagradditions:molten_inferium')
  craftopia.hide('mysticalagradditions:molten_prudentium')
  craftopia.hide('mysticalagradditions:molten_soulium')
  craftopia.hide('mysticalagradditions:molten_suprenium')
  craftopia.hide('mysticalagradditions:molten_tertium')
  craftopia.hide('pneumaticcraft:biodiesel')
  craftopia.hide('pneumaticcraft:diesel')
  craftopia.hide('pneumaticcraft:etching_acid')
  craftopia.hide('pneumaticcraft:ethanol')
  craftopia.hide('pneumaticcraft:gasoline')
  craftopia.hide('pneumaticcraft:kerosene')
  craftopia.hide('pneumaticcraft:lpg')
  craftopia.hide('pneumaticcraft:lubrifiant')
  craftopia.hide('pneumaticcraft:memory_essence')
  craftopia.hide('pneumaticcraft:oil')
  craftopia.hide('pneumaticcraft:plastic')
  craftopia.hide('pneumaticcraft:vegetable_oil')
  craftopia.hide('pneumaticcraft:yeast_culture')
  craftopia.hide('sliceanddice:fertilizer')
  craftopia.hide('tconstruct:beetroot_soup')
  craftopia.hide('tconstruct:blazing_blood')
  craftopia.hide('tconstruct:earth_slime')
  craftopia.hide('tconstruct:ender_slime')
  craftopia.hide('tconstruct:honey')
  craftopia.hide('tconstruct:ichor')
  craftopia.hide('tconstruct:liquid_soul')
  craftopia.hide('tconstruct:magma')
  craftopia.hide('tconstruct:meat_soup')
  craftopia.hide('tconstruct:molten_aluminum')
  craftopia.hide('tconstruct:molten_amethyst')
  craftopia.hide('tconstruct:molten_amethyst_bronze')
  craftopia.hide('tconstruct:molten_brass')
  craftopia.hide('tconstruct:molten_bronze')
  craftopia.hide('tconstruct:molten_cinderslime')
  craftopia.hide('tconstruct:molten_clay')
  craftopia.hide('tconstruct:molten_cobalt')
  craftopia.hide('tconstruct:molten_constantan')
  craftopia.hide('tconstruct:molten_copper')
  craftopia.hide('tconstruct:molten_debris')
  craftopia.hide('tconstruct:molten_diamond')
  craftopia.hide('tconstruct:molten_electrum')
  craftopia.hide('tconstruct:molten_emerald')
  craftopia.hide('tconstruct:molten_ender')
  craftopia.hide('tconstruct:molten_enderium')
  craftopia.hide('tconstruct:molten_glass')
  craftopia.hide('tconstruct:molten_gold')
  craftopia.hide('tconstruct:molten_hepatizon')
  craftopia.hide('tconstruct:molten_invar')
  craftopia.hide('tconstruct:molten_iron')
  craftopia.hide('tconstruct:molten_lead')
  craftopia.hide('tconstruct:molten_lumium')
  craftopia.hide('tconstruct:molten_manyullyn')
  craftopia.hide('tconstruct:molten_netherite')
  craftopia.hide('tconstruct:molten_nickel')
  craftopia.hide('tconstruct:molten_obsidian')
  craftopia.hide('tconstruct:molten_osmium')
  craftopia.hide('tconstruct:molten_pig_iron')
  craftopia.hide('tconstruct:molten_platinum')
  craftopia.hide('tconstruct:molten_quartz')
  craftopia.hide('tconstruct:molten_queens_slime')
  craftopia.hide('tconstruct:molten_refined_glowstone')
  craftopia.hide('tconstruct:molten_refined_obsidian')
  craftopia.hide('tconstruct:molten_rose_gold')
  craftopia.hide('tconstruct:molten_signalum')
  craftopia.hide('tconstruct:molten_silver')
  craftopia.hide('tconstruct:molten_slimesteel')
  craftopia.hide('tconstruct:molten_steel')
  craftopia.hide('tconstruct:molten_tin')
  craftopia.hide('tconstruct:molten_uranium')
  craftopia.hide('tconstruct:molten_zinc')
  craftopia.hide('tconstruct:mushroom_stew')
  craftopia.hide('tconstruct:potion')
  craftopia.hide('tconstruct:powdered_snow')
  craftopia.hide('tconstruct:rabbit_stew')
  craftopia.hide('tconstruct:scorched_stone')
  craftopia.hide('tconstruct:seared_stone')
  craftopia.hide('tconstruct:sky_slime')
  craftopia.hide('tconstruct:venom')
  craftopia.hide('vintage:sulfur_dioxide')
  craftopia.hide('vintage:sulfur_trioxide')
  craftopia.hide('vintage:sulfuric_acid')
})

// Categories
JEIEvents.removeCategories(craftopia => {
  craftopia.remove([
      'twilightforest:uncrafting'
  ])
})

const $MekanismJEI = Java.loadClass('mekanism.client.jei.MekanismJEI')
JEIEvents.hideCustom(event => {
  event.get($MekanismJEI.TYPE_GAS).hideAll()
  event.get($MekanismJEI.TYPE_INFUSION).hideAll()
  event.get($MekanismJEI.TYPE_PIGMENT).hideAll()
  event.get($MekanismJEI.TYPE_SLURRY).hideAll()
})


// This File has been authored by Craftopia Staff.
  